# Generated by Django 3.2.7 on 2021-10-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoring_category', models.CharField(max_length=200)),
                ('TopStockID', models.IntegerField()),
                ('Code', models.CharField(max_length=200)),
                ('close', models.FloatField()),
                ('start_date', models.CharField(max_length=200)),
                ('End_date', models.CharField(max_length=200)),
                ('Date_StartDate', models.CharField(max_length=200)),
                ('Year_StartDate', models.IntegerField()),
                ('Quarter_StartDate', models.IntegerField()),
                ('Month_StartDate', models.IntegerField()),
                ('Day_StartDate', models.IntegerField()),
                ('Week1_ROI', models.FloatField()),
                ('Week1PandL', models.FloatField()),
                ('Week1PecentGain', models.FloatField()),
                ('Week2_ROI', models.FloatField()),
                ('Week2PandL', models.FloatField()),
                ('Week2PecentGain', models.FloatField()),
                ('Week4_ROI', models.FloatField()),
                ('Week4PandL', models.FloatField()),
                ('Week4PecentGain', models.FloatField()),
                ('Week8_ROI', models.FloatField()),
                ('Week8PandL', models.FloatField()),
                ('Week8PecentGain', models.FloatField()),
                ('Week12_ROI', models.FloatField()),
                ('Week12PandL', models.FloatField()),
                ('Week12PecentGain', models.FloatField()),
                ('Week24_ROI', models.FloatField()),
                ('Week24PandL', models.FloatField()),
                ('Week24PecentGain', models.FloatField()),
            ],
        ),
    ]
